### PR TITLE
fixed gate val on note off in MidiTriggerToCV

### PR DESCRIPTION
**Pull request by jeremywen**
Not using data2 here because some implementations do not send a zero velocity for note off.  As discussed here https://www.facebook.com/groups/vcvrack/permalink/137757963551023/

My original video is in the facebook post.  My video of the fix working is here: 
https://www.youtube.com/watch?v=hD70UqUqoV4&feature=youtu.be

### CODE REVIEW

**Comment by jeremywen** [comment]
I was told to tag you @bontric on this issue.

**Comment by bontric** [comment]
This is correct. I guess I didn't notice this since my controllers send Note On messages with velocity 0 instead of Note Off messages.

**Comment by jeremywen** [comment]
Can you merge it? or does @AndrewBelt need to review it?

**Comment by bontric** [comment]
I don't have write access to the repo, so @AndrewBelt has to accept it. Don't know why he hasn't done this yet but I guess he'll come back to this when he finds the time.

**Comment by AndrewBelt** [comment]
Thanks

**Comment by ebunders** [comment]
@AndrewBelt  Is there a reason not to apply this patch to the v0.5 branch? It is a rather annoying bug and the fix seems to have zero impact on anything else. I have no idea when the next release is supposed to be branched from master, so yeah.

**Comment by AndrewBelt** [comment]
Yes, because I'm avoiding backports from master in the v0.5 branch. But I've merged it *just for you* for v0.5.1.

**Comment by ebunders** [comment]
You are sweet! Also I have been able to build the project myself, and I will add some extended build instructions to the wiki, as I have already done for the Jack support build instructions.
It's fun to play around with a c++ codebase and work out how it's put together. I did a fair bit of java and such, but now I feel like a man... :-)

**Pull request merged**
