### PR TITLE
[WIP] midi interface revamp

### PR DESCRIPTION
**Pull request by bontric**
## Note: This is still work in progress to discuss structuring/implementation

# List from #81
- [x] MIDI-to-CV
	- [x] 1V/oct, gate, velocity, pitchwheel, mod, volume, aftertouch outputs
	- [ ] MIDI clock output, start/stop gate, song reset outputs **(Note: Will be implemented in another module)**
	- [x] LED for each output
	- [x] Be able to use the two interfaces on the same port, useful for MIDI channels
- [ ] Quad MIDI-to-CV
	- [ ] polyphonic voice asignment modes (rotate, reset, reasign)
	- [ ] 4x 1V/oct, 4x gate, 4x velocity outputs
	- [ ] pitchwheel, mod, volume outputs
	- [ ] LED for each gate
- [x]  MIDI CC-to-CV
	- [x] grid of 16 CC voltage outputs
	- [x] select source CC channel for each port by clicking the dropdown on each one
	- [x] LEDs for each output
- [ ] CV-to-MIDI
	- [ ] 1V/oct, gate, velocity, pitchwheel, mod inputs
	- [ ] MIDI clock, start/stop gate, song reset inputs
	- [ ] LED for each input

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Great work, they look amazing! I like the idea of LEDs on the corner of ports.
2017-10-08-014808_448x427_scrot
I wonder if TextFields would be better for CC channel names instead of ChoiceButtons, but yeah, that's about the only feedback I can think of.

**Comment by bontric** [comment]
Glad you like it! 

How about I polish the MIDI-to-CV and MIDI-CC-To-CV modules for the v0.4.0 release?  I'll work on the others after.

The TextFields for CC channel selection is a good idea. I tried that out before, so the switch is not a big deal. I'll look into that today. 

I'll also add a background and screws to make the modules look nice for v0.4.0.

**Comment by AndrewBelt** [comment]
All sounds good.

**Comment by AndrewBelt** [comment]
Just thought it might be useful to have a "Panic" button on the MIDI to CV to clear all notes and reset the outputs. That method should also probably be called when you switch audio devices.

If there's no room on the panel, maybe it could go in the context menu or when the user hits Initialize (instead of closing the device).

**Comment by bontric** [comment]
Okay, I'll look into that as well. 

I have a minor issue with using text fields:

The backspace key is defined for `ModuleWidget`

```c++
Widget *ModuleWidget::onMouseMove(Vec pos, Vec mouseRel) {
	// Instead of checking key-down events, delete the module even if key-repeat hasn't fired yet and the cursor is hovering over the widget.
	if (glfwGetKey(gWindow, GLFW_KEY_DELETE) == GLFW_PRESS || glfwGetKey(gWindow, GLFW_KEY_BACKSPACE) == GLFW_PRESS) {
		if (!guiIsModPressed() && !guiIsShiftPressed()) {
			gRackWidget->deleteModule(this);
			this->finalizeEvents();
			delete this;
			// Kinda sketchy because events will be passed further down the tree
			return NULL;
		}
	}
	return OpaqueWidget::onMouseMove(pos, mouseRel);
}
```
Therefore pressing `delete` in a text field within a ModuleWidget will remove the Module widget. Any suggestion on how to handle this?

**Comment by AndrewBelt** [comment]
Fixed with 2cbe7c3

**Comment by bontric** [comment]
Perfect, thanks!

Similar problem: Using the arrow keys will scroll in Rack instead of navigation within a text field

**Comment by AndrewBelt** [comment]
Fixed e6d56d8
Thanks, that should be it. The only other place is in MIDIToCVInterface where I have some commented-out code that reads keys in a future attempt to make a MIDI computer keyboard.

**Comment by bontric** [comment]
> Just thought it might be useful to have a "Panic" button on the MIDI to CV to clear all notes and reset the outputs. That method should also probably be called when you switch audio devices.

I've added the panic button  (0314a72) and text fields for midi cc number selection  (f633de1 The commit says "for channel selection", my bad)

It would be nice if TextFields had a "onTextChange" function which is called whenever the user changes the input. For now, I used the `draw` function to implement this, but it adds some unnecessary overhead (Not really problematic, but I guess an `onTextChange` callback could be useful for other implementations as well).

```c
void CCTextField::draw(NVGcontext *vg) {
	if (text.size() > 0) {
		if (*inited) {
			*inited = false;
			text = std::to_string(*ccNum);
		}
		try {
			*ccNum = std::stoi(text);
			// Only allow valid cc numbers
			if (*ccNum < 0 || *ccNum > 127) {
				text = "";
				begin = end = 0;
			}
		} catch (...) {
			text = "";
			begin = end = 0;
		}
	};
	TextField::draw(vg);
}
```

Not so releveant, but is there a good way to customize the TextField or ChoiceButton themes? 
Right now i see reimplementing the `draw()` method as the only option. (Since you only use TextFields and ChoiceButtons for the main UI, I guess this has not been relevant, but could be useful)

If you want I can implement the TextField and ChoiceButton theming, and implement an `onTextChange` function for `TextFields`. Either in this pull request or I create a separate one.

**Comment by AndrewBelt** [comment]
Added `onTextChange()` event with e9cddb1

**Comment by bontric** [comment]
> Ready to merge after that?

Yeah,  I think this is done.

**Comment by AndrewBelt** [comment]
So after merging, a discussion on Facebook convinced me to add cable LEDs #80. I added that and then realized that the LEDs on the jacks of the MIDI interfaces are redundant. But they are still useful since LEDs only appear if a cable is plugged into them. Would it make sense to turn them into activity meters? For example, when any of the values are changed, it would blink with exponential decay. I could add this feature if you like, whatever sounds best.

**Comment by bontric** [comment]
First of all, the cabel LEDs look great!

I think the cable LEDs are enough. Having a second LED to indicate change might be a bit overkill. The light intensity is enough to indicate change for CC parameters and the Gate basically indicates a change for the MIDI-to-CC module. As of now, I can't think of another use for them, so I'd suggest we remove the corner LEDs

Also: I just realized we need to call the `resetMidi()` function when the Channel changes as well. (If a Note is pressed on Channel 2 while "All" is selected, a switch to e.g. Channel 1 will lead to the note not being released. )

**Comment by AndrewBelt** [comment]
Yeah, might be best to remove them then. 

For these changes, you or me?

**Comment by bontric** [comment]
I can do that quickly

**Pull request merged**
