### PR TITLE
Change the color of the cables with CTRL+right click

### PR DESCRIPTION
**Pull request by The-XOR**
This is a tiny modification but I believe it could help to in case of complicated patches.
Right-clicking a port while holding down the CTRL key does not disconnect the cable but change it's color.  Also, the sequence of the color assignment for future connections is updated.

### CODE REVIEW

**Comment by Coirt** [comment]
Interesting, this seems like a very useful feature and a good alternative for #1453

**Comment by Coirt** [comment]
Had a chance to test this on windows 7. Works amazingly well. 

Nice!! @The-XOR

**Comment by CyaNox** [comment]
In my opinion you shouldn't include my PR in yours even though I appreciate the complement.

Having both this and my PR will make merging kind of a mess when it comes to the proper git references as your commit doesn't actually reference mine.

Your PR is for a nice tweak to the cable handling as it describes in the title and therefore shouldn't really include other changes.

**Comment by AndrewBelt** [comment]
I usually don't accept PRs to Rack. Closing.
See https://github.com/VCVRack/Rack/issues/569 for a discussion of this issue.

**Pull request closed without merging**
