### PR TITLE
Several fixes so it actually builds and runs

### PR DESCRIPTION
**Pull request by falkTX**
Take whatever if you feel it's worth importing, or close if you don't like it.
I just patched in things to make it run for me.
Sadly without the resources for the plugins there's not much I can use...
But I was able to get into this state http://i.imgur.com/lR04amv.png

Thanks again for the great project, hope you can continue to work on it.

### CODE REVIEW

**Comment by chrisbeckstrom** [comment]
this project looks AMAZING!!!! So extremely excited. I cloned and tried to compile, but got lots of errors related to the missing noc and oui submodules. Cloned @falkTX 's fork (you're awesome @falkTX I'm a kxstudio user and absolutely freaking love it) but get the error
`src/plugin.cpp:12:17: fatal error: zip.h: No such file or directory`

I'm not much of a coder but I think that means I'm just missing a file called `zip.h`. Any idea where I could get it?

At any rate thanks for doing this; if you need testers I am ALL over that, as long as I can actually get it to build on my system :-)

**Comment by AndrewBelt** [comment]
Sorry, I should have mentioned that this repo is unsupported until Knobcon. Development is a mix of private and public until then.

**Comment by falkTX** [comment]
I expected something like that.
Do you still think it's possible you can upload the resource files for the plugins? If so, I can manage the rest on my own for now.

**Comment by AndrewBelt** [comment]
...Patience...

**Comment by AndrewBelt** [comment]
Added up-to-date /res files. As I gradually synchronize my local repo with the GitHub repo, it will become easier to build on platforms other than mine. Since I've fixed most of the files from your PR, I'm closing this now.

I'm actually amazed you were able to get most of this working in the state the GitHub repo was. Bravo!

**Comment by falkTX** [comment]
Thank you :)

Is it now ok to send PRs for general fixing, or should I wait a bit longer?

**Comment by AndrewBelt** [comment]
Sure, go ahead. At worst, I just won't get to them before Beta release.

**Pull request closed without merging**
