### PR TITLE
[WIP] MIDI clock to CV

### PR DESCRIPTION
**Pull request by bontric**
I started working on the midi clock and it seems to work pretty well so far. 

I used this Molten [CV-SYNC](http://www.moltenvoltage.com/products/CV_SYNC_by_Molten_Voltage_-_MIDI_Clock_to_CV_Synchronizer.html) Module as reference. 

However, we could easily add more ratios. 

TODO: 
+ ~~If you switch the ratio, you need to start/stop the external clock~~ [FIXED]
+ ~~If you change the clock's speed you need to start/stop the external clock~~ [FIXED]
+ Add cv input for ratio selection. 
+ Add "Continue" message output

@AndrewBelt I'd like to split the MidiInterface modules into multiple files to get a better overview. Is that OK with you?

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Haven't checked this out yet, but splitting into multiple files is fine. To avoid polluting core.hpp up with RtMidi stuff, you could make a MidiInterface.hpp header with the RtMidi includes.

**Comment by bontric** [comment]
I'll restructure that over the weekend.

The clock timing issues should be resolved. It would be good if someone could test this with another clock to see if it works as well.

I have a small issue with [SEQ3](https://github.com/VCVRack/Fundamental/blob/master/src/SEQ3.cpp).
Triggering the **reset** should not play the first note, if an external clock is connected. 
The midi start message will trigger the reset and send a tick just shortly after that. The clocks will still be in sync, but SEQ3 will be one step ahead of the midi device.

I think:

```c++
	// Reset
	if (resetTrigger.process(params[RESET_PARAM].value + inputs[RESET_INPUT].value)) {
		phase = 0.0;
		index = 8;
                if (inputs[EXT_CLOCK_INPUT].active == false) {
			nextStep = true;
                }
		resetLight = 1.0;
	}
```

should fix this.

## TODO: 
* Add cv input for ratio selection. 
* Add "Continue" message output

**Comment by AndrewBelt** [comment]
You might want to have a look the last few posts of #223.

**Comment by bontric** [comment]
I'm closing this and create a new, more general pull request for the midi modules.

**Pull request closed without merging**
