### PR TITLE
Module browser: keep previews setting.

### PR DESCRIPTION
**Pull request by NoxyNixie**
> Added a setting (enabled by default) that keeps the module previews in memory forever. This makes it so that module previews aren't cleared out of memory when they have not been rendered for >60 frames making the module browser much more responsive at the cost of memory.

With this setting enable the module browser only has to build the previews once which makes the module browser several orders of magnitude more responsive on my system (1000+ modules (pretty much all the free plugins)).

I also checked on the memory overhead and in my opinion its not that bad:

Startup: 83,880K
Scrolled down with keep previews: 334,316K
Scrolled down without keep previews: 200,312K

Therefor the additional memory usage in my case is 134M which to me is definitely worth it since now the browser does not have to rebuild any previews which makes it near instant.

Looking at the code the only place where these previews are used and deleted is the module browser initially I just removed the whole rack::app::ModelBox::deletePreview() and any accesses to it (which works) but does not allow people with more restrictive memory to have the old behavior. So I made it a setting.

### CODE REVIEW

**Comment by VegaDeftwing** [comment]
Please for the love of god merge this. As is Rack is painfully slow when opening up on a HiDPI screen with lots of modules installed (Arch Linux, Latest. Ryzen 1700. AMD-Vega56)

**Comment by AndrewBelt** [comment]
If preview framebuffers aren't deallocated, wouldn't rendering 1000+ modules crash Rack when you run out of GPU RAM or interfere with other programs that need GPU RAM?

**Comment by Coirt** [comment]
Curious, would it not crash anyway if you did ever run out of GPU RAM?

**Comment by AndrewBelt** [comment]
`FramebufferWidget` fails gracefully when it can't allocate a framebuffer, displaying just an empty widget. But when you're running low on GPU RAM, the OS can kill the application, or the screen can lock up for a number of seconds and in rare cases, indefinitely.

**Comment by VegaDeftwing** [comment]
Hmm, well at the very least making it a config option would be greatly
appreciated. As of right now it's unpleasant to use, at least on my system

**Comment by Coirt** [comment]
There is definitely room to improve, I noticed with heavy patches it can be a bit sluggish. 

Wondering would having versions of panels for the browser, which already have their components displayed make it any better. It would require new panels that dev's could implement somewhat easily depending on pack size.

**Comment by CyaNox** [comment]
With this patch applied:
procexp64_2019-07-16_16-53-24

Without this patch:
procexp64_2019-07-16_16-56-33


The screenshots are made after I generated all the previews by scrolling all the way down the list of 1069 (almost all the free modules). After which I scrolled up and down a little bit near the bottom.

With this patch enabled it is quite clear that the GPU memory utilization is more however the performance is near 100% once all the previews have been made. If you look at the screenshot without the patch applied the performance is horrendous even after having gone down all the way in the module browser.

My GPU is not amazing at all (an AMD Radeon HD 6670 1GB) and clearly aging ... but I'd still run with this patch since as you can see the overhead is not that bad. I would however still keep this a setting so that if people actually have worse GPU's or about 10 times as many plugins loaded they can still run Rack without crashing (I have yet to test what actually happens if the GPU runs out of memory with and without this patch).

**Comment by CyaNox** [comment]
> Wondering would having versions of panels for the browser, which already have their components displayed make it any better.

Unlikely since the FBO will still use as much ram and the "preview version" panel would still need to be rendered into the FBO.

**Comment by Coirt** [comment]
> > Wondering would having versions of panels for the browser, which already have their components displayed make it any better.
> 
> Unlikely since the FBO will still use as much ram and the "preview version" panel would still need to be rendered into the FBO.

Right but it would not need to read and locate code in different locations to get the positions of components which could cut render time down. Even if it is a small performance increase over the long haul it might be quicker.

**Comment by VegaDeftwing** [comment]
I don't necessarily think asking module devs to include screenshots is the best move, but on higher end systems with the VRAM to spare something needs to be done. I can comfortably run an insane number of modules and would love to be able to have as many choices as possible, but browsing since v6.x is actually worse for me now as I have to wait sometimes upwards of a minute for anything to happen. I do think it would make more sense to both keep previews in ram (total VRAM or setting file dependent) and/or, possibly, cache a rendered version of the module previews to disk.

on the note of things crashing when VRAM gets low, would it be possible to just detect the amount of total and available VRAM and do 'permanent' caching if there's plenty to spare but be more careful when there's not? I see the struggle of trying to make everyone from the RTX2080ti to the intel iGPU owners happy here.

I can not stress how poor the module browser performance is for me at the moment despite overkill hardware. I hope to compile with this patch applied sometime in the next few days and I'll try to do a long term test running radeontop and htop to monitor my system.

**Comment by AndrewBelt** [comment]
To render module previews, the SVG panels and components must be read off the disk. Do you have a slow disk like a hard drive, @VegaDeftwing?

**Comment by VegaDeftwing** [comment]
No, I'm on an nvme.

**Comment by CyaNox** [comment]
For the sake of testing I recompiled with `MODEL_BOX_ZOOM = 2.0f;` which effectively multiplies the memory usage by **16** and this is the result:
image

You can see in the `Dedicated GPU Memory` graph where I hit my GPU memory limit while I'm scrolling down the list of 1069 modules. The list happily keeps scrolling and the module previews (albeit grossly large) keep rendering perfectly fine:
image

In the `Commited GPU Memory` you can roughly see where I ended up at the end of the module list and from that point on I could scroll rapidly from top to bottom in the module browser (to be able to rapidly scroll you need #1475).

I'm not seeing any missing or not rendering modules at all.

**Comment by CyaNox** [comment]
This one is no longer correct due to branch changes. #1492 is the continuation.

**Pull request closed without merging**
